- hosts: all
  tasks:
    - name: installing apache on RedHat
      yum: name=httpd state=present
      notify: starting apache
  handlers:
    - name: starting apache
      service: name=httpd state=started
