- hosts: all
  tasks:
    - name: installing git on redhat
      yum: name=git state=present
      when: ansible_os_family=="RedHat"
    - name: installing maven on debian
      apt: name=maven state=present
      when: ansible_os_family=="Debian"
