---
- name: install package
  hosts: all
  tasks:
  - name: install git
    yum: name=git* state=absent
  - name: install tree
    yum: name=tree* state=absent
  - name: instal maven
    yum: name=maven* state=absent 
